//AUTH
export const SAVE_SESSION = 'SAVE_SESSION';
export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const GET_INTEREST = 'GET_INTEREST';
export const CONFIRM_EMAIL = 'CONFIRM_EMAIL';
export const CONFIRM_CODE = 'CONFIRM_CODE';
export const SAVE_INTEREST = 'SAVE_INTEREST';
export const GOOGLE_LOGIN = 'GOOGLE_LOGIN';
export const GOOGLE_SIGNUP = 'GOOGLE_SIGNUP';
export const GOOGLE_FAIL = 'GOOGLE_FAIL';
export const GROUP_FAIL = 'GROUP_FAIL';

//ACTIVITY
export const CREATE_ACTIVITY = 'CREATE_ACTIVITY';
export const GET_ACTIVITY = 'GET_ACTIVITY';
export const DELETE_ACTIVITY = 'DELETE_ACTIVITY';
export const UPDATE_ACTIVITY = 'UPDATE_ACTIVITY';


//mUSIC
export const GET_MUSIC = 'GET_MUSIC';

//FAVORITES
export const GET_FAVORITES = 'GET_FAVORITES';

//STORIES
// export const CREATE_PRAYER = 'CREATE_PRAYER';
export const GET_STORIES = 'GET_STORIES';
// export const DELETE_PRAYER = 'DELETE_PRAYER';
// export const UPDATE_PRAYER = 'UPDATE_PRAYER';


//MEDITATION
// export const SEND_MSG = 'SEND_MSG';
export const GET_MEDITATIONS = 'GET_MEDITATIONS';
export const SET_FAV = 'SET_FAV';
export const GET_MEDCATEGORIES = 'GET_MEDCATEGORIES';
export const GET_STORCATEGORIES = 'GET_STORCATEGORIES';
export const GET_SOUNCATEGORIES = 'GET_SOUNCATEGORIES';
export const GET_SUBSCRIPTION = 'GET_SUBSCRIPTION';
export const PAYMENT = 'PAYMENT';
export const UPDATE_USER = 'UPDATE_USER';
export const FORGOT_PASS = 'FORGOT_PASS';
export const GET_IMAGES = 'GET_IMAGES';
export const POST_CONTACT = 'POST_CONTACT'; 
export const UPDATE_DATA = 'UPDATE_DATA'; 


export const VALIDATE_PLAYER = 'VALIDATE_PLAYER'; 
export const SAVE_MEDI = 'SAVE_MEDI'; 
export const SAVE_MEDICAT = 'SAVE_MEDICAT'; 
export const CLEAR_MEDI = 'CLEAR_MEDI'; 
export const CONNECTION_CHECK = 'CONNECTION_CHECK'; 

// export const DELETE_CHAT = 'DELETE_CHAT';
// export const UPDATE_CHAT = 'UPDATE_CHAT';
